apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freelance-radar
  namespace: freelance-radar
  annotations:
    external-dns.alpha.kubernetes.io/hostname: freelance-radar.k8s-demo.de
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    cert-manager.io/cluster-issuer: letsencrypt-hetzner
spec:
  tls:
    - hosts:
        - freelance-radar.k8s-demo.de
      secretName: freelance-radar-tls
  rules:
    - host: freelance-radar.k8s-demo.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: freelance-radar
                port:
                  number: 80
