apiVersion: v1
kind: Service
metadata:
  name: freelance-radar
  namespace: freelance-radar
spec:
  type: ClusterIP
  selector:
    app: freelance-radar
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
