apiVersion: v1
kind: Secret
metadata:
    name: grafana-credentials
    namespace: grafana
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:BYPWYio=,iv:hMNBa4z+TLngPc05TvASphAxvKO44DmHYQdXj6blZmI=,tag:ZiNbce9abi94942WoLFStw==,type:str]
    admin-password: ENC[AES256_GCM,data:qNgASt6KrjSqRCuWxATKlnIQKL3gUa39YkYfEwbB,iv:AdYxJQ1F09ROdOWEQ5mygTGUqq5LNaExAKJ7ATcn1f0=,tag:rCowhVtE7Ek2WLRUNcPMQw==,type:str]
sops:
    age:
        - recipient: age14sld8g4w55d8elus7jk3wq6wup0276d7lsafxnrr630au9gh9y7s79ydvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dVo0cFRIUVYzbjRCb01a
            WXppd1BLeW81YjBFS0djVDF0RGRNUW1BNDNNClBVUlB6ZVBpeDZOM2pLcjhhTE5R
            eEY1aStuTFgzWTlrY1ZKMHRJUDhRRGcKLS0tIGloY1cyNUFsdE5DYkNMcTNiU2lV
            TEsyQWZwbE82ZEROTk55TmExVFVpMmMKY7AoJbd2jqOKFK0cxkRGMqjkzd6G1Q8G
            uVjDrAkYvw4N8uhtYMaFGP0Q4fD6I6mUmlOq4ZvBrt5Em9r+TkRFwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-03T15:30:22Z"
    mac: ENC[AES256_GCM,data:OUzae6Bn5n1oacLiUCXM18ws6mhtoNFvbMeVXyISf43jNPfElrMDwHg/4z/TH/DbHYb81gBKr5GYA3pifgnLkKkdIfn2C2sBQUWealfNOJ/x5rUNL1GQE00nWPT81ySfkfvz7L7tHAsrEpPIgDkCSjz28c576najm6jw0cYnFCc=,iv:fdrM+bHfmYV+CXTbihEeRbpVcu1k7jTdrXllBM4hwDU=,tag:1xazJqB2WAA9nLAy6ry8Qw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
