apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - webhook-repository.yaml
  - webhook-release.yaml
  - hetzner-secret.yaml
  - clusterissuer-hetzner.yaml
  - clusterissuer-hetzner-staging.yaml
