apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-api
  annotations:
    external-dns.alpha.kubernetes.io/hostname: demo-api.k8s-demo.de
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    cert-manager.io/cluster-issuer: letsencrypt-hetzner
spec:
  tls:
    - hosts:
        - demo-api.k8s-demo.de
      secretName: demo-api-tls
  rules:
    - host: demo-api.k8s-demo.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo-api
                port:
                  number: 80
