apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-traefik
    namespace: kube-system
type: Opaque
stringData:
    CF_API_TOKEN: ENC[AES256_GCM,data:EPHEG0OnzfTtY9wgiUrc8NLY1Xt2GnBSvdaxEyIAobtvpQwXNgB7Hg==,iv:32xaYCSrbY4ttuBylUqEK/7PPa7rxmtVT6e7ZdAKRMg=,tag:ZpXbAXe7Aw0CjGKJ3cookw==,type:str]
sops:
    age:
        - recipient: age14sld8g4w55d8elus7jk3wq6wup0276d7lsafxnrr630au9gh9y7s79ydvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMDhwNXdxMFpqbjZLb3BW
            dGVMQjUvVExqdjloQWlzV2JpYlBhTVhJSHljCm9CT051bC9mTUtzNUFKUnVnSHFw
            eWtBMWFqYno5ejJzNXNoWHVXN3grQk0KLS0tIFM0YzN6NU1sQ2E0UDBDekZVY2E2
            aHA0NHVpbFUxSXZLNXhTYXF4dkFEMEkK8HMvPu2atUHi1yVvQ58mHYFNqcZy3aIP
            LTcPPLfCMPn8LGcdVY7giBUouC+P8+ZunTtKY3Ahzy/gB/v39dVxvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T15:26:51Z"
    mac: ENC[AES256_GCM,data:qc7bYkCFksPRJnXNYsGmGZYhGAGh3D+9CfIQI+XFbkrqYjN5AqI1VYpjii2ee5g9gQPg3/pTdgmgDBWBGyHQdnSfQsSvALl6os/lbrb20seyVACPDQUW/MjZjVX19k+4Tom/yWPM7oKPH5G6MScCIF3QalE06BveqINWFvuVOeY=,iv:hm8/aEkGkUBX6WOmmqTyXIHCD9HPJjFiLWAnYKnkQkc=,tag:iVc/44iGnhDmWygvPOpAqg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
