apiVersion: v1
kind: Secret
metadata:
    name: hetzner-traefik
    namespace: kube-system
type: Opaque
stringData:
    HETZNER_API_KEY: ENC[AES256_GCM,data:yZhyT0HM2FgcFK2F4K6YieFhakeAVQdOO0a7j/ZpZIfWh1mT05EhemcYvNhk+jJtBbrJvO8el7lzzIOHIr3q7g==,iv:zh2BNK7ZJnJ1IiQIBn+a57mV5OhNulpSKRa3Gbtxkuk=,tag:tjpmCT0ih2EG1aqz0wRxog==,type:str]
sops:
    age:
        - recipient: age14sld8g4w55d8elus7jk3wq6wup0276d7lsafxnrr630au9gh9y7s79ydvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMU3NPa0h4NXFrVVh2cEd1
            Y2haQVNqVGY3MGxzNWoyL20rVTRGQ2JoVGpBCmNXbGl6NGZJZE5Mc3lDNzYrdGp5
            SG5hdzk4ZEIzNXNhRnZiNHhzN2pjbDAKLS0tIGVUZTJmRnluWFpwYm9KbkNCU3Nj
            aWN5cjFCYTBBL290VGlsc3JpSW1GZmcKHhB5AvvAvwCQ/l92YMViC79myAbCllDE
            SaYPuRP1zJx8sYB1D5nIsKYG2D96hPV0by3Imn2wWatKYt1dCH+YOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T09:57:45Z"
    mac: ENC[AES256_GCM,data:qZpnXvypwOOyR0XoTaKXZVDwA+byk29Xc0aOngrPGgBLLeNV0kyUjxfZjAnJUfoIzLbR/020O0Dkz72YOCXzhmPJbLhflyppDQgFEV3cQUmCUTqB1u+UG22Hgn1zhDsiUieBhIU6Yw7twuTh7QrM5nbWnCFaxr+YPnfqk/CFasg=,iv:uuAQFYgFSG5y+V6ONveqFMtmT4aKAsuG9rH9UGAiEg4=,tag:IinonfxnlcOTNq7NlkX6vA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
