apiVersion: v1
kind: Secret
metadata:
    name: hetzner-traefik
    namespace: kube-system
type: Opaque
stringData:
    HCLOUD_TOKEN: ENC[AES256_GCM,data:KUB2Xbsp4FvXGamU0e36TF3Jq3+S9vn9NbIodhtVBCqYzn0DbMun4xvsd78dryXAQ0sFywX43uFUtGDssPUx7g==,iv:BhgWKgCAqdBdlZQHyJKtbvuAuiyu73fT4Xw1q8CEBa4=,tag:MG+TSbv1aeAB7aACMYliYA==,type:str]
sops:
    age:
        - recipient: age14sld8g4w55d8elus7jk3wq6wup0276d7lsafxnrr630au9gh9y7s79ydvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybDh5TjlwMk5MMEhSR2hL
            bXpHZWJ4b25xZ2pwdmZVdlllRC9MQ0NqcWlvCll4cG1BOFVCL3FLL3k4TXJKbDJo
            S2VYcllSRG5WT3lBdFdMYVRkOExQbjgKLS0tIFN4S3NoT0Y1R295Y1BjWlp1UTZy
            dmVFTGU3ZXNja0NhckhOTmdBdSs4SGMKo3eHP7yF/jkwc3HJlBZoNLVaIFdebH+Y
            ximvBroA9b70SQmf16PJdsuqrV37jiO7sm/CdZtPy7HUAeZb6Poz4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-21T10:08:16Z"
    mac: ENC[AES256_GCM,data:M2h+sNGcattk4En2SbKK4+368wAQu4V6xivuOPQZjHoU3WxpO5lVMnbiPrrHBGJaF9YS8BXxO7A6GqI0uCBSkApBFEfyW3um4mVvkix3NXTFY3FSolCSDTZO+97ykDW1u//jFQyK3KC1kne0ruSP0eRogf+nnxT7TtlTUyh6mtQ=,iv:qWkEh2CTD2h5Y1XDPXjRTJ0jMHQ4fG/jZjMyj7UCA80=,tag:i1gXPIw8dhP5/kcpiSIqzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
