apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wp-ai-chatbot-redirect
  annotations:
    external-dns.alpha.kubernetes.io/hostname: wp-ai-chatbot.k8s-demo.de
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: default-wp-ai-chatbot-redirect@kubernetescrd
spec:
  rules:
    - host: wp-ai-chatbot.k8s-demo.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wp-ai-chatbot-redirect
                port:
                  number: 80
