apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - linkding
  - wallabag
  - demo-api
  - cluster-dashboard
  - demo-django
  - tested-django
  - wordpress
  - grafana
  - prometheus
  - node-exporter
  - kube-state-metrics
  - loki
  - promtail
  - tempo
