apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hotel-package
  namespace: hotel-package
  annotations:
    external-dns.alpha.kubernetes.io/hostname: hotelpackage.kubetest.uk
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    cert-manager.io/cluster-issuer: letsencrypt-cloudflare
spec:
  tls:
    - hosts:
        - hotelpackage.kubetest.uk
      secretName: hotel-package-tls
  rules:
    - host: hotelpackage.kubetest.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hotel-package
                port:
                  number: 80
