apiVersion: v1
kind: Secret
metadata:
    name: prometheus-basic-auth
    namespace: prometheus
type: Opaque
stringData:
    #ENC[AES256_GCM,data:lO3O9O/a1bdt1ae4u9y+R7WDixlcU6oRl67WOphdqxmKipQ=,iv:/NaTFqw4XxYSXTyLuuROPehbqMOw1TD9NriQBaJ7fSc=,tag:5CIAEP138w9gmrC4m8kTfQ==,type:comment]
    #ENC[AES256_GCM,data:ogKkWCoaKaEOySdetY4wx50t+pFibPUh648acyis/vLj9GrkFSP2jd3aPT/R,iv:RfFUmoWCP9nxuRJysn5pFX6tksfa65bkEkdak9eVfbk=,tag:OVwkDu9QD2QbnLpptk4yLA==,type:comment]
    #ENC[AES256_GCM,data:LqcPrhs03Vd/UPLbhX18lxDkbDE=,iv:2HmvocPMI55S+vPYHZvrpYLpH4/DW/2K+qtGGOHWH/Q=,tag:5uC75+BfXUiYoQ6Ok2IPzQ==,type:comment]
    users: ENC[AES256_GCM,data:Wy1n04pW/07idpsS+SWANz+0tMCF9ajU0rmi6ZyZtJ4KtKuMR2Qn,iv:tKn+TxXQk55EvjeaGgS/AzD2iV6AHeceCoRfDoTy+1M=,tag:7h+6+K3y5xjrn+HshbCrMg==,type:str]
sops:
    age:
        - recipient: age14sld8g4w55d8elus7jk3wq6wup0276d7lsafxnrr630au9gh9y7s79ydvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaUlVmbjdIWDcxYkc1cTlP
            WFBaSjJRMVViaDdQblJLS1hrMmdRcktwNVY4CmJQNG0vZUVzSmVvcG5uTjRNRkxK
            NDkveVl6M0toeHQxcndMQmY2WTFIdkUKLS0tIDFWZXlMZmdTY3JkcGZIRmx6NFA3
            RXpRekZuRng5NHdOSHRWcW5QSmFDZWcKTUMNxEFrX2AxQQZFo7N3Vv1f983Hv+DZ
            iLWZQz2AjeyBrAEZFlpAdvlQgsRjbCBMVWrtElkW6aoeCXkk22764w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-04T11:37:43Z"
    mac: ENC[AES256_GCM,data:36O/37AVApqYs6LKeimgyMkGwfot7k3yIcFUYadDU/ZbBjSLTbbpAcTpr5B4W6Q//RoNVZZWTLeQKy/4tCPWJQazM1bcVQP+7ZCfhbW4/sRliWRYMjsWzmXN+9EN5FsO8NHkf9P4Jay00iOg8ZyebmYlcmyW3/IwZh4JVGVzNsw=,iv:/9/gaofSCc2BDzN0Fj3gCbc+XOwtIFrMQaeYRBSLxwc=,tag:Hw0w11ero+F1cBWYnEillQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
