apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexus-docker-registry
  annotations:
    external-dns.alpha.kubernetes.io/hostname: docker-registry.k8s-demo.de
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
    # Enable large uploads for Docker images
    traefik.ingress.kubernetes.io/router.middlewares: default-docker-registry-size@kubernetescrd
spec:
  rules:
    - host: docker-registry.k8s-demo.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexus
                port:
                  number: 8082
