apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linkding
  annotations:
    external-dns.alpha.kubernetes.io/hostname: linkding.k8s-demo.de
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    cert-manager.io/cluster-issuer: letsencrypt-hetzner
spec:
  tls:
    - hosts:
        - linkding.k8s-demo.de
      secretName: linkding-tls
  rules:
    - host: linkding.k8s-demo.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: linkding
                port:
                  number: 9090
